version: "3"
services:
  db:
    image: mariadb:latest
    container_name: webpro-db
    ports:
      - "127.0.0.1:33062:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: webpro-db